# Generated by Django 4.2.5 on 2023-09-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0002_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ("name",),
                "verbose_name": "Dish",
                "verbose_name_plural": "Dishes",
            },
        ),
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(default=0),
        ),
    ]
