# Generated by Django 4.2.5 on 2023-10-06 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0003_alter_dish_options_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={"ordering": ("-id",)},
        ),
    ]
